### ISSUE TITLE
Man page man-db cache failure

### ISSUE THREAD

**Issue by satmandu** [PCRE2Project/pcre2#160]
Running `mandb -c` I get this with the 10.40 version of pcre2...

```
mandb: warning: /usr/local/share/man/man3/pcre2demo.3.zst: whatis parse for pcre2demo(3) failed
```

**Comment by PhilipHazel** [comment]
pcre2demo(3) is a man page that lists the pcre2demo.c program so that it is available to those who don't necessarily have the PCRE2 source files. I have modified the script that generates it so that the output from "man" is still a valid C program, but the source no longer causes "mandb -c" or lexgrog to grumble. At least, not on my box - please reopen this if there is still an issue.

**Comment by satmandu** [comment]
Thanks! We'll see if it causes any more issues after the next tagged pcre2 release, when we package again!
