### ISSUE TITLE
multiple recent changes made to pcre2.h.in without updating pcre2.h.generic

### ISSUE THREAD

**Issue by saurik** [PCRE2Project/pcre2#205]
The file src/pcre2.h.in is instantiated as src/pcre2.h.generic with the version numbers filled in, which I guess sadly requires that every change made to pcre2.h is made twice. (I wonder... is there no way to split this header file into just the version number and then the rest of the content? ;P) Recently, while the changes from 303e3bc48086b1a1501511c48a400d7b6a92a9bd to pcre2.h.in were included in pcre2.h.generic, the changes from c13d54f6581fa51a270a1ec40b1b7626d686dec1, a6089462a460a9f6c2db63a86e1c09fabaa81499, and c80c6338ad23380544a79ba2325a93113e8168d3 were not, causing an inconsistent drift in the available definitions.

**Comment by PhilipHazel** [comment]
pcre2.h.generic is automatically generated when a release is being prepared using "make dist" (the code is in Makefile.am). This dates back to the days before PCRE2 was on GitHub. pcre2.h itself is generated from pcre2.h.in when somebody runs ./configure. There is a similar issue with config.h.generic, but no double editing is required. These days I do usually remember to run the script that updates the HTML docs when I edit the "man" versions. I will now try to remember to run the relevant Make targets when pcre2.h.in is edited, and do it soon so that everything is in step.

**Comment by PhilipHazel** [comment]
I have updated and pushed pcre2.h.generic.
