### ISSUE TITLE
The SSH connection fails when pcre2 of the gcov version is used.

### ISSUE THREAD

**Issue by JetXujing** [PCRE2Project/pcre2#225]
To reproduce the problem, perform the following steps:
1. Add "-fprofile-arcs -ftest-coverage" option to CFLAGS.
2. Compile and install pcre2.
3. ssh connection in the new shell window.

According to the preceding steps, the SSH connection fails:
![image](https://user-images.githubusercontent.com/43668249/231742064-a0374b58-bf9b-4d87-bfe9-e93628f88c20.png)

**Comment by zherczeg** [comment]
What is the point of this report? You added coverage info, installed the lib, ssh probably used it, gcc tried to write coverage info into root directory without permission, crash. This is nothing to do with the library.

**Comment by JetXujing** [comment]
What I want to say is that adding coverage information should not affect pcre2 functions. According to the result, SSH directly or indirectly uses pcre2, and I am not sure whether the problem is caused by permission.

**Comment by zherczeg** [comment]
This repository is for pcre2 development. You modified the operation of the library. If you are not sure, the issue is not caused by your modification, don't report a bug.

Coverage collection usually (not always, sometimes it triggers compiler bugs, or cause timing issues) does not have side effects. However, the collected data is written back to the disk before exit, usually where the binary is. In your case, that is your `/lib/something`. It is normally write protected, so it cause a crash.

**Comment by JetXujing** [comment]
Okay, I understand. Thank you.
