### ISSUE TITLE
Variable-length lookbehind

### ISSUE THREAD

**Issue by mvorisek** [PCRE2Project/pcre2#269]
This is a feature request to add variable-length lookbehind support.

Javascript and NET regex engines support this feature for a long time already, Perl engine supports this feature as experimental since 2021.

Simple example: https://regex101.com/r/RvuZ1r/1

**Comment by PhilipHazel** [comment]
Perl's implementation seems very restricted. Your regex101 example won't be acceptable because it contains x+. The Perl documentation states  that the only variable-length lookbehinds it supports must have a maximum length of no more than 255. Thus, you can have x{2,200} (for example), but not x+. This seems to me to be somewhat too restrictive.

I have been wondering how more general variable-length lookbehinds could be implemented in PCRE. For them to be truly general, I think the code has to run the lookbehind group on a substring of the subject that starts at the very beginning and ends at the current point. This could be quite time-consuming, but it might not be unbearable. I plan on doing some experiments.

**Comment by zherczeg** [comment]
This would require to support soime extremely complicated cases. I remember v8 (Chrome) stated to support variable lookbehind, but I was able to write a pattern without much effort where it did not work correctly. And ecmascript regex is considerably simpler than pcre2 regex. A costly matching from the beginning of the pattern could work, but it would be way too slow.

A better alternative could be matching sub-patterns to strings captured by capturing blocks. This way the user could limit the scope of the search.

**Comment by PhilipHazel** [comment]
For fully general support, I think you *have* to go back to the beginning. I know it will be slow, but perhaps in some cases this won't be too bad. I'm thinking of cases like pcre2grep, where matching subjects are usually quite short lines. Anyway, I want to do some tests to get an idea of how slow it might be. For example, I'd like to compare   X\d+\KY   against  (?<=X\d+)Y   with different string lengths. I will report on what I find.

**Comment by PhilipHazel** [comment]
It turns out that it doesn't take much code to make pcre2_match() do variable-length lookbehind in a simple way (though I probably haven't ironed out all the bugs). I modified pcre2_compile() so that instead of rejecting a variable length lookbehind, it set the lookbehind length to its maximum (65535). The I added a loop to pcre2_match() that steps back character by character from the current point, trying the assertion at each, until either it matches, or reaches the start of the subject. During the assertion, the end of the subject is temporarily set at the current point, and at the end of the assertion there is a check that the current point has been reached before proceeding with the rest of the match.

With this code, I did some simple timing tests. I compared the pattern  `X\d+\KY.`  with `(?<=X\d+)Y.`  with different lengths of subject, using pcre2test's timing and ability to generate long strings. The subject was  `\[Z]{N}X1234567890Y1Y2` where N was replaced by different numbers to get different string lengths. Both patterns matched `Y1` in all cases. This is pretty crude, but the timings were interesting. I used the following values of N: 1, 10, 100, 1000. With start-up optimizing turned on (the default), The \K pattern's time was 0.0001 and the lookbehind's time was 0.0002 or 0.0003 for all four string lengths. I also tried a negative lookbehind, which correctly matched `Y2` but for which there is no \K equivalent. This gave different times for the four lengths: 0.0005, 0.0007, 0.0015, and 0.0104. Then I ran all the tests with no_start_optimize, and there was a lot of difference:

\K pattern:   0.0002  0.0004  0.0027  0.0262
Pos LB:       0.0018  0.0027  0.0564  4.9541
Neg LB:      0.0022  0.0033  0.0591  4.9799

It is, of course, not surprising that the start-up optimizations make a lot of difference. The tests were all done with the 8-bit library in non-UTF mode. This was just one particular test; I suppose patterns that cannot take advantage of the start-up optimizations would fare badly.

CONCLUSION:  For shortish subjects this isn't as bad as I feared. The patch is not much code, though perhaps there are still some side effects to fix. It could be constrained by, for example, limiting the maximum lookbehind character count to 256 (as Perl does) or to a user-settable value. It could be documented to be inefficient in certain cases. Needless to say, it breaks JIT at the moment, and I haven't looked at whether it could be implemented for pcre2_dfa_match() (probably not easily).

Comments, please!

**Comment by PhilipHazel** [comment]
OK, there is now code in HEAD for people to test. I have not yet updated the documentation, but that is my next task. The HEAD code supports variable lookbehinds in a similar way to Perl - indeed, the test cases are all Perl-compatible. Only lookbehinds that have a maximum matching length are supported. The default maximum is 255 characters - the same as Perl - but there is a function that can be used to change this. Thus,  (?<=X{3,10})  is supported, but (?<=X+) is not.

The support is only in pcre2_match(). There is no support in pcre2_dfa_match(), and no JIT support, though I hope Zoltan will consider adding JIT support in due course. (Zoltan: I added a new opcode called OP_VREVERSE with min/max values for each branch.)

OH DEAR. I see that the Windows and MacOS test builds on GitHub have failed. I must have broken something. I will investigate.

**Comment by PhilipHazel** [comment]
I fixed a typo in CMakeLists.txt which has made the MacOS test run OK, and I finally managed to find out what I'd forgotten to update in RunTest.bat so all tests on GitHub are now running successfully.

**Comment by PhilipHazel** [comment]
The documentation is now updated and I have enabled \R in lookbehinds, which I had overlooked.

**Comment by PhilipHazel** [comment]
Closing this issue as dealt with.
