### ISSUE TITLE
Is there a way to copy `pcre2_code` but using different memory allocation functions?

### ISSUE THREAD

**Issue by freak82** [PCRE2Project/pcre2#291]
Hi there,

I've a use case where I need to copy given `pcre2_code` but I need to use different memory allocation functions for the new copy.
The `pcre2_code_copy` can't be used because it uses the memory allocation functions from the source `pcre2_code` object.

The only way that I could find to implement such functionality is to use the `pcre2_serialize_encode` and then `pcre2_serialize_decode` functions and get a copy of the original `pcre2_code` object but using different `pcre2_general_context` with different memory allocation functions. 
However, this workaround has a drawback in terms of the allocation size of the copied `pcre2_code` object when the original object used the default tables. The problem is that, as far as I checked, the `pcre2_serialize_encode` serialize the tables no matter if the default tables are used or not and then `pcre2_serialize_decode` does additional allocation for the tables in the copied-to object even though the original `pcre2_code` was using the default tables. This additional allocation was 1112 bytes as far as I checked.

So, I'm still wondering if there is a way for copying a `pcre2_code` object but using different memory allocation functions for the copy.
For context why I need this. I've multi-threading application where each thread has it's own memory arena and everything which lives in given thread is allocated from its memory arena. The threads don't communicate with each other once everything is initialized. The threads only communicate during the initialization phase. However, the application needs to be able to start as fast as possible and the initialization of the regex objects (there are hundreds of them) is done asynchronously by a different thread and then these objects are then sent to the worker threads to be copied and used there.

Thanks,
Pavel.

**Comment by PhilipHazel** [comment]
The serialize encode function includes the tables because decoding might happen in an environment where the default tables are different. There is no way at present of making pcre2_code_copy() use a different allocator, but would it be possible for you to make your allocator into a "virtual allocator" that chooses the actual allocator by consulting some externally-settable parameter? So you would set some parameter before calling pcre2_compile() and before calling pcre2_code_copy() to tell the allocator where to allocate in each case. I realize this might not be simple or even possible with multiple threads, but it's the only thought that I've come up with (other than implementing a new function, of course).

**Comment by freak82** [comment]
Thanks for the idea for "virtual allocator". I think I can use it. I just need to think a bit more how to make it fit in the current abstractions but I think it's doable.

**Comment by PhilipHazel** [comment]
Excellent. The late, great David Wheeler https://www.computer.org/profiles/david-wheeler said that many computing problems can be solved by adding another layer of indirection, a principle I have used quite often.
