### ISSUE TITLE
Inconsistency with ungreedy variable lookaheads

### ISSUE THREAD

**Issue by addisoncrump** [PCRE2Project/pcre2#347]
I have bisected this issue to dc5f96663597572f694147aeec3525003c351123.

```
$ ./pcre2test -jit
PCRE2 version 10.43-DEV 2023-04-14 (8-bit)
  re> /(?>.+?)/endanchored
data> abcd
No match
data> abcd\=no_jit
 0: d
```

**Comment by zherczeg** [comment]
This is an atomic bug issue, and not a lookahead. It is caused by early aborting of non-greedy iterator, which is incorrectly handled by first character optimizer. There are similar open bugs as this, and I think I can make more.

**Comment by zherczeg** [comment]
16759fc099731fd1af3dfdf7a4663fcdb579d2fd this change (more like a rework) is the start of the fixing the underlying issue here. Hence it does not fix all cases (e.g #359), but the atomic block case should work now. However, this is a high risk change, but fuzzers should be able to test this quite well. @addisoncrump could you check if this patch breaks valid cases (i.e. it works without this patch, but wrong with this patch)?

**Comment by addisoncrump** [comment]
I have launched the fuzzers on the change linked and will let you know :slightly_smiling_face:

**Comment by addisoncrump** [comment]
I'm not seeing situations where the old implementation is correct and the new implementation is incorrect, but I found a couple additional testcases that don't need endanchored:

```
PCRE2 version 10.43-RC1 2023-12-27 (8-bit)
  re> /(?>\D*|)A/
data> (?>\\D*|)A
 0: A
data> (?>\\D*|)A\=no_jit
No match
data> 
  re> /(?>.+|)]/
data> (?>.+|)]
 0: ]
data> (?>.+|)]\=no_jit
No match
```

Interpreter and perl are in alignment.

**Comment by addisoncrump** [comment]
This is the basic pattern of all the fuzzer-discovered cases, actually.

**Comment by zherczeg** [comment]
Ok, I disabled atomic blocks for this optimization. It looks like not exhausting all cases has all kinds of side effects.

**Comment by addisoncrump** [comment]
Okay, we can reopen this if you want to apply optimisations in the future.
