### ISSUE TITLE
Old files on pcre.org

### ISSUE THREAD

**Issue by Neustradamus** [PCRE2Project/pcre2#387]
Dear @PCRE2Project, @PhilipHazel,

There are two old files:
- https://pcre.org/news.txt
- https://pcre.org/changelog.txt

Maybe others?

Time to update?

Thanks in advance.

**Comment by carenas** [comment]
I think the following quote from the website (at the bottom of the last page) is still accurate though:

`Please note that neither this website nor the SourceForge download repositories are maintained by Philip. Please report website or SourceForge PCRE project problems to` [webmaster@pcre.org](mailto:webmaster@pcre.org).

Updated documentation (as web pages) is available in the release package and update regularly as well (as linked in the README) in the following url:

 [https://pcre2project.github.io/pcre2/doc/html/index.html]( https://pcre2project.github.io/pcre2/doc/html/index.html)

**Comment by Neustradamus** [comment]
@carenas: I have sent an e-mail to webmaster...

**Comment by PhilipHazel** [comment]
The website is going to be under new management sometime soon - I was waiting for that to be completed before commenting here, but the issue could be closed.

**Comment by PhilipHazel** [comment]
The web site has been updated, so I'm closing this.

**Comment by Neustradamus** [comment]
@PhilipHazel: Now you can manage the website?
Domain name and hosting?

**Comment by PhilipHazel** [comment]
The web site has been taken over by a new webmaster, not me.

**Comment by Neustradamus** [comment]
@PhilipHazel: It will be never lost?
The domain name, the website?

**Comment by PhilipHazel** [comment]
I cannot predict the future! I expect it will last as long as the current owner is willing to support it.

**Comment by PhilipHazel** [comment]
Nick, here is some more history for your entertainment. :-)  The PCRE2 project only moved to GitHub in 2021. Prior to that it had been hosted on a University of Cambridge (virtual) box that was the successor of a number of open-source hosts in the University, dating back to the 1990s. There were several open-sources hosted there, including Exim, but that moved off shortly after I retired and left that project in 2007. PCRE and then PCRE2 were using Subversion for source control. The move to GitHub was spurred on by the University Information Services wanting to tidy up their world (I don't think there was anything else left on their host by that time).

Now, a long time before that, quite early in the lifetime of PCRE, Andrew Ho offered to set up and maintain pcre.org because there was no other web site and I wasn't in a position to handle one. He maintained it for many years, but recently has less time to devote (and the site got rather out of date). There was an offer from Brian Altstatt <altstattb@dotcom-monitor.com> to give some resource to the PCRE2 project, and what has happened is that he took over pcre.org from Andrew. 

Incidentally, Andrew Ho also used to maintain an unofficial mirror on SourceForge, but I think that is now obsolete (perhaps this was only for PCRE1).  I was quite happy to let him get on with these things because before I retired I had plenty to do keeping both Exim and PCRE maintained (and writing/updating the Exim books), and after I retired we just went along with the status quo.

Your are right that the GitHub front page is now "official", but I don't think pcre.org should be abolished, because over the decades, people have got used to looking at it.

**Comment by NWilson** [comment]
That's great Philip, thank you for that history! It's good to know who the people involved are, so can correspond in future as necessary.

**Comment by Neustradamus** [comment]
Have you recover the pcre domain/website?

**Comment by NWilson** [comment]
No. We do have ownership or control of pcre.org.

I appreciate your concern for the project, but we cannot address any issues you file here regarding pcre.org, or Sourceforge. We do not own them.
