### ISSUE TITLE
Earlier configure options still available and up-to-date? --enable-utf and --enable-unicode-properties

### ISSUE THREAD

**Issue by capiman** [PCRE2Project/pcre2#436]
https://github.com/CESNET/libyang/tree/devel

There is mentioned:

libpcre2 >= 10.21 (including devel package)

    note, that PCRE is supposed to be compiled with unicode support (configure's options --enable-utf and --enable-unicode-properties)

It looks like these are not more available in latest version.
Are there now different switches for this? Or somehow enabled by default?

PS: Notice:
configure.ac still mentions --enable-utf in a comment...

**Comment by PhilipHazel** [comment]
The current option for "configure" is --disable-unicode because Unicode support is the default. This has always been the case for PCRE2 (the 10.xx series). This option controls both UTF support and Unicode property support. The options you mention were used by PCRE1 (the 8.xx series). The comment in configure.ac is a bug! It should have been updated for PCRE2, but has managed to live for almost 10 years! I will correct it; thanks for reporting it.

**Comment by capiman** [comment]
Many thanks for the fast clarification!
